routes/inventory_routes.py
import json
import string
import uuid

import bleach
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user

from database_functions import get_user_inventories, delete_item_from_inventory, \
    add_item_to_inventory, \
    find_inventory, find_inventory_by_slug, \
    find_user_by_username, edit_inventory_data, \
    delete_inventory_by_id, add_user_to_inventory, delete_user_to_inventory, find_inventory_by_id, add_user_inventory, \
    regenerate_inventory_token, find_inventory_by_access_token, add_user_to_inventory_from_token

import strings

inv = Blueprint('inv', __name__)


__OWNER = 0
__COLLABORATOR = 1
__VIEWER = 2
__PRIVATE = 0
__PUBLIC = 1
__READ_ONLY = 2


@inv.context_processor
def inject_front_end_strings():
    """
    Inject strings into the front end
    :return:
    """
    return dict(strings=strings)


@inv.context_processor
def my_utility_processor():
    def item_tag_to_string(item_tag_list):
        tag_arr = []
        for tag in item_tag_list:
            tag_arr.append(tag.tag.replace("@#$", " "))
        return ",".join(tag_arr)
    return dict(item_tag_to_string=item_tag_to_string)


@inv.route(rule='/inventories', methods=['GET'])
@login_required
def inventories():
    """
    Flask route to retrieve the inventories.

    Returns:
        The rendered HTML template with the following variables:
            - username (str): The current user's username.
            - inventories (list): The inventories for the current user.
            - user_is_authenticated (bool): Indicates if the user is authenticated.
            - number_inventories (int): The number of inventories minus one (excluding the 'hidden' default inventory).
    """
    user_is_authenticated = current_user.is_authenticated
    user_invs = get_user_inventories(current_user_id=current_user.id,
                                     requesting_user_id=current_user.id, access_level=-1)

    number_inventories = len(user_invs) - 1  # -1 to count for the 'hidden' default inventory

    return render_template(template_name_or_list='inventory/inventories.html', username=current_user.username, inventories=user_invs,
                           user_is_authenticated=user_is_authenticated, number_inventories=number_inventories)


@inv.route('/@<string:username>/inventories')
def inventories_for_username(username):
    current_user_id = None
    requesting_user_id = None
    if current_user is not None:
        user_is_authenticated = current_user.is_authenticated
    else:
        user_is_authenticated = False

    if user_is_authenticated:
        current_user_id = current_user.id
        if username != current_user.username:
            user_ = find_user_by_username(username=username)
            if user_ is not None:
                requesting_user_id = user_.id
                username = user_.username
            else:
                return render_template(template_name_or_list='404.html', message=strings.no_inventory_string), 404
        else:
            requesting_user_id = current_user.id
            username = current_user.username

    user_invs = get_user_inventories(current_user_id=current_user_id,
                                     requesting_user_id=requesting_user_id,
                                     access_level=-1)

    if len(user_invs) == 0:
        return render_template(template_name_or_list='404.html', message=strings.no_inventories_string), 404

    number_inventories = len(user_invs) - 1  # -1 to count for the 'hidden' default inventory

    return render_template(template_name_or_list='inventory/inventories.html',
                           inventories=user_invs, username=username,
                           user_is_authenticated=user_is_authenticated,
                           number_inventories=number_inventories)


@inv.route('/inventory/<int:inventory_id>')
@login_required
def inventory(inventory_id: int):
    inventory_ = find_inventory(inventory_id=inventory_id)
    if inventory_ is not None:
        if inventory_.owner_id == current_user.id:
            return redirect(url_for(endpoint='items.items_with_username_and_inventory',
                                    username=current_user.username, inventory_slug=inventory_.slug))

    return render_template(template_name_or_list='404.html', message=strings.no_inventory_string), 404


@inv.route(rule='/inventory/add', methods=['POST'])
@login_required
def add_inventory():
    """
    Add Inventory

    Adds a new inventory to the system with the provided name, description, access level, and user ID.

    Returns:
        None

    Invocation:
        The method is invoked using a POST request to the '/inventory/add' route.

    Parameters:
        None

    Returns:
        None

    Exceptions:
        None

    Preconditions:
        - The user must be logged in.
        - The request must contain the 'inventory_name' and 'inventory_description' fields in the request form.
            - If 'inventory_name' is None or an empty string, the method will redirect to the 'inv.inventories' route.
            - If 'inventory_description' is None, it will be set to an empty string.

    Postconditions:
        - If the 'inventory_public' field is present in the request form, the access level of the new inventory will be set
          to __PUBLIC. Otherwise, it will be set to __PRIVATE.
        - The 'inventory_name' and 'inventory_description' values will be cleaned using the 'bleach.clean()' method.
        - The 'add_user_inventory' function will be called with the cleaned 'inventory_name', 'inventory_description',
          'access_level', and 'user_id' parameters.
        - If the 'add_user_inventory' function returns a non-None 'new_inventory_data' value, the method will redirect to
          the 'items.items_with_username_and_inventory' route with the current user's username and the new inventory's slug.
        - Otherwise, the method will redirect to the 'inv.inventories' route.

    Example Usage:
        response = add_inventory()
    """
    inventory_name_ = request.form.get("inventory_name")
    inventory_description_ = request.form.get("inventory_description")
    if inventory_name_ is None or inventory_name_ == "":
        return redirect(url_for('inv.inventories'))
    if inventory_description_ is None:
        inventory_description_ = ""

    inventory_name_ = bleach.clean(inventory_name_)
    inventory_description_ = bleach.clean(inventory_description_)

    access_level_ = __PRIVATE
    if "inventory_public" in request.form:
        access_level_ = __PUBLIC

    new_inventory_data, msg = add_user_inventory(name=inventory_name_, description=inventory_description_,
                                                 access_level=access_level_, user_id=current_user.id)

    if new_inventory_data is None:
        return redirect(url_for('inv.inventories'))

    return redirect(url_for(endpoint='items.items_with_username_and_inventory', username=current_user.username,
                            inventory_slug=new_inventory_data["slug"]))


@inv.route(rule='/inventory/delete', methods=['POST'])
@login_required
def del_inventory():
    json_data = request.json
    inventory_ids = json_data.get('inventory_ids')
    if inventory_ids is not None:
        delete_inventory_by_id(inventory_ids=inventory_ids, user_id=current_user.id)

    return redirect(url_for('inv.inventories'))


@inv.route(rule='/inventory/edit', methods=['POST'])
@login_required
def edit_inventory():
    inventory_id = bleach.clean(request.form.get("inventory_id"))
    inventory_name = bleach.clean(request.form.get("inventory_name"))
    inventory_description = bleach.clean(request.form.get("inventory_description"))

    access_level_ = __PRIVATE
    if "inventory_public" in request.form:
        access_level_ = __PUBLIC

    edit_inventory_data(user_id=current_user.id, inventory_id=int(inventory_id), name=inventory_name,
                        description=inventory_description, access_level=int(access_level_))

    return redirect(url_for('inv.inventories'))


@inv.route(rule='/inventory/deleteuser', methods=['POST'])
@login_required
def delete_user_to_inv():
    inventory_id = request.json.get("inventory_id")
    user_id = request.json.get("user_id")

    inventory_id = bleach.clean(inventory_id)
    user_id = bleach.clean(user_id)

    try:
        inventory_id = int(inventory_id)
        user_id = int(user_id)
    except Exception:
        return redirect(url_for('inv.inventories'))

    result = delete_user_to_inventory(inventory_id=inventory_id, user_to_delete_id=user_id)

    inventory_ = find_inventory_by_id(inventory_id=inventory_id, user_id=current_user.id)

    if result:
        return redirect(url_for(endpoint='items.items_with_username_and_inventory',
                                inventory_slug=inventory_.slug,
                                username=current_user.username).replace('%40', '@'))
    else:
        return redirect(url_for(endpoint='items.items_with_username_and_inventory',
                                inventory_slug=inventory_.slug,
                                username=current_user.username).replace('%40', '@'))


@inv.route(rule="/regenerate-token>", methods=["POST"])
@login_required
def regenerate_token():
    if request.method == 'POST':
        json_data = request.json
        inventory_id = json_data['inventory_id']
        new_token = uuid.uuid4().hex
        token_ = regenerate_inventory_token(user_id=current_user.id,
                                            inventory_id=inventory_id,
                                            new_token=new_token)

        if token_ is not None:
            return json.dumps({'success': True, "new-token": token_}), 200, \
                   {'ContentType': 'application/json'}
        else:
            return json.dumps({'success': False, "new-token": ""}), 400, \

templates/inventory/_add_inventory_form.html
<form method="post"
      action="{{ url_for('inv.add_inventory') }}">

    <hr>

    <div class="row">
        <div class="col-12">
            <label for="inventoryName" class="form-label">Name:</label>
            <input type="text" class="form-control" name="inventory_name" id="add_form_inventory_name" required>
        </div>
    </div>

    <br>
    <div class="row">
        <div class="col-12">
            <label for="inventoryDescription" class="form-label">Description:</label>
            <input type="text" class="form-control" name="inventory_description" id="add_form_inventory_description">
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-sm-2">
        <label>Visibility</label>
        </div>
        <div class="col-sm-10">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="inventory_public" name="inventory_public">
                <label class="form-check-label" for="inventory_public">Public inventory</label>
             <div id="emailHelp" class="form-text">Items in public inventories will be visible by anyone but not editable </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-sm-2">
            <label>Type
        </label>
        </div>
        <div class="col-sm-10">
            <select class=" form-select"  id="inventory_type" name="inventory_type" aria-label="Default select example">
                <option selected>Inventory</option>
                <option value="1">List</option>
            </select>
             <div id="emailHelp" class="form-text">Physical inventory or simple list of things</div>
        </div>
    </div>
    <hr>

    <div class="row">
        <hr>

        <div class="col-12">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input type="hidden" class="form-control" name="username" id="form_username" value="{{ username }}">
            <button type="submit" class="btn btn-primary">Save</button>
            <button class="btn btn-primary">Cancel</button>
        </div>

    </div>

</form>

<hr>

<div class="row">
    <div class="col-md-12 text-center">
        <h5>Or use access code to access another user's inventory...</h5>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">

                <form method="post"
                      action="{{ url_for('inv.register_for_inventory_access') }}">

                    <div class="row">
                        <div class="col-12">
                            <label for="inventoryName" class="form-label">Access token:</label>
                            <input type="text" class="form-control" name="access_token" id="access_token"
                                   required>
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <div class="col-12">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>

                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

templates/inventory/_edit_inventory_form.html
<form method="post"
      action="{{ url_for('inv.edit_inventory') }}">

    <hr>
  <div class="mb-3 row">
        <label class="col-sm-2">Visibility<br>
            <small class="text-danger">Take care</small>
        </label>
        <div class="col-sm-10">
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" id="edit_form_inventory_public" name="inventory_public">
              <label class="form-check-label" for="inventory_public">Public inventory</label>
            </div>
        </div>
    </div>
    <hr>

    <div class="row">

        <div class="col-12">
            <label for="edit_form_inventory_name" class="form-label">Name:</label>
            <input type="text" class="form-control" name="inventory_name" id="edit_form_inventory_name">
        </div>

    </div>

    <br>
    <div class="row">

        <div class="col-12">
            <label for="edit_form_inventory_description" class="form-label">Description:</label>
            <input type="text" class="form-control" name="inventory_description" id="edit_form_inventory_description">
        </div>

    </div>

    <br>

    <br>

    <div class="row">
        <hr>

        <div class="col-12">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input type="hidden" class="form-control" name="inventory_id" id="edit_form_inventory_id" value="">
            <button type="submit" class="btn btn-primary">Save</button>
            <button class="btn btn-primary">Cancel</button>
        </div>

    </div>

</form>

templates/inventory/_inventory-table.html
{% if number_inventories > 0 %}
    <table class="table  dataTable" id="inventories-table">
        <thead class="success">
        <tr>
            <th></th>
            <th data-priority="1"></th>
            <th></th>
            {% if user_is_authenticated %}
                <th></th>

            {% endif %}
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for inventory_data in inventories %}
            {% if "__default__" not in  inventory_data['inventory_name'] %}
                <tr>
                    <td>
                        <a href="{{ url_for('items.items_with_username_and_inventory', username=inventory_data['inventory_owner'], inventory_slug=inventory_data['inventory_slug']) | replace('%40', '@') }}">
                            {{ inventory_data['inventory_name'] }}</a>
                    </td>
                    <td>{{ inventory_data['inventory_description'] }}</td>
                    <td>
                        {{ inventory_data['inventory_item_count'] }} item(s) | @{{ inventory_data['inventory_owner'] }}
                        |
                        {% if  inventory_data['inventory_access_level'] == 1 %}
                            <span class="fas fa-unlock" style="color:red;"
                                  data-toggle="tooltip" data-placement="top" title="{{ strings.this_inventory_is_public_tooltip }}"
                            ></span>
                        {% else %}
                            <span class="fas fa-lock"
                                  data-toggle="tooltip" data-placement="top" title="{{ strings.this_inventory_is_not_public_tooltip }}"
                            ></span>
                        {% endif %}
                        {% if inventory_data['userinventory_access_level'] == 1 %}
                            | Collaborator
                        {% elif inventory_data['userinventory_access_level'] == 2 %}
                            | Viewer
                        {% endif %}
                    </td>

                    {% if user_is_authenticated %}

                        {% if inventory_data['userinventory_access_level'] == 0 %}

                            <td>
                            <span class="fas fa-edit fa-2x" data-bs-toggle="collapse"
                                  id="inventoryEdit-{{ inventory_data['inventory_id'] }}"
                                  href="#collapseInventoryEdit"
                                  data-inventory-id="{{ inventory_data['inventory_id'] }}"
                                  data-inventory-name="{{ inventory_data['inventory_name'] }}"
                                  data-inventory-description="{{ inventory_data['inventory_description'] }}"
                                  data-inventory-slug="{{ inventory_data['inventory_slug'] }}"
                                  data-inventory-public="{{ inventory_data['inventory_access_level'] }}"

                                  data-toggle="tooltip" data-placement="top" title="{{ strings.edit_inventory_tooltip }}"
                                  style="display: inline-block; margin-right: 20px;"></span>
                            </td>

                        {% else %}
                            <td>Remove</td>
                        {% endif %}

                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value=""
                                       data-inventory-id="{{  inventory_data['inventory_id'] }}"
                                       id="selected-item-{{  inventory_data['inventory_id'] }}">
                            </div>
                        </td>

                    {% endif %}
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="row">
        <div class="col-md-12">
            <div class=" text-center">
                <h5>Oh no, no inventories :(</h5>

                <p>You can add a new inventory by clicking the <i class="fas fa-plus"></i> icon at the top.</p>
            </div>
        </div>
    </div>
{% endif %}

templates/inventory/_inventory_help.html
<p>Inventories are collections of objects forming a common theme, such as your
    collection of retro computers your partner hates, or your collection of Mongolian tooth flossing sticks.</p>

<p>You can add a new inventory by clicking the <i class="fas fa-plus"></i> icon at the top. Along with the inventory <em>name</em>
and <em>description</em>, you can specifiy whether the inventory will be private (default) or allow item level visibility.
Item level visibility allows items within the inventory to be publically viewable. By default, items are created private.</p>

<p>The <i class="fas fa-lock"></i> icon indicates that the inventory is private (to you).
    The <i class="fas fa-unlock" style="color:red;"></i> indicates an inventory with item level visibility. </p>

<p>Items (or more precisely things) can be moved between inventories from within the inventories themselves. </p>

templates/inventory/inventories.html
{% extends "base.html" %}

{% block content %}

    <div class="content">
        <div class="container">

            <div class="row">
                <div class="col-12">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            aria-label="Close"></button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <h4 class="mb-0">Inventories <small>| {{ number_inventories }} </small></h4>
                                </div>
                                <div class="col-md-4">
                                    <div class="text-end">
                                        {% if user_is_authenticated %}
                                            <span class="fas fa-plus fa-2x"
                                                  data-toggle="tooltip" data-placement="top"
                                                  title="{{ strings.add_new_inventory_tooltip }}"
                                                  data-bs-toggle="collapse"
                                                  href="#collapseInventoryAdd"
                                                  style="display: inline-block; margin-right: 20px;"></span>
                                            <span class="fas fa-info fa-2x"
                                                  data-toggle="tooltip" data-placement="top"
                                                  title="{{ strings.basic_help_tooltip }}"
                                                  data-bs-toggle="collapse"
                                                  href="#collapseInventoryHelp"
                                                  style="display: inline-block; margin-right: 20px;"></span>


                                            <a id="delete-inventories-btn-collapse" data-bs-toggle="collapse"
                                               href="#collapseDeleteInventories"
                                               role="button" aria-expanded="false"
                                               data-toggle="tooltip" data-placement="top" title="Delete location"
                                               aria-controls="confirmInventoryDelete">
                                                <span id="delete-inventories-span" class="fas fa-minus fa-2x"
                                                      style="color:lightgray; display: inline-block; margin-right: 20px;cursor: pointer;"></span>
                                            </a>

                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-md-12">
                                    {% if user_is_authenticated %}
                                        <div class="collapse" id="collapseInventoryAdd" aria-expanded="false">
                                            <div class="card card-body">
                                                <h5>Add new inventory:</h5>
                                                {% include 'inventory/_add_inventory_form.html' %}
                                            </div>
                                        </div>

                                        <div class="collapse" id="collapseInventoryEdit" aria-expanded="false">
                                            <div class="card card-body">
                                                <h5>Edit inventory:</h5>
                                                {% include 'inventory/_edit_inventory_form.html' %}
                                            </div>
                                        </div>

                                    {% endif %}

                                    <div class="collapse" id="collapseInventoryHelp" aria-expanded="false">
                                        {% include 'inventory/_inventory_help.html' %}
                                        <hr>
                                    </div>

                                    <div class="collapse" id="collapseDeleteInventories" aria-expanded="false">
                                        <div class="text-center">
                                            <p>{{ strings.delete_confirm_string }}</p>
                                            <button id="confirm-delete-inventories-btn" type="button"
                                                    class="btn btn-primary btn-sm">{{ strings.delete_string }}
                                            </button>
                                            <button id="cancel-delete-inventories-btn" type="button"
                                                    class="btn btn-primary btn-sm">{{ strings.cancel_string }}
                                            </button>
                                            <hr>
                                        </div>
                                    </div>
                                    {% include 'inventory/_inventory-table.html' %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block footer %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/thinglist.js') }}"></script>

    <script type="text/javascript">
        const username = {{ username|tojson|safe }}
        const csrf_token = {{ csrf_token()|tojson|safe }}
        const delete_inv_url = {{ url_for('inv.del_inventory')|tojson|safe}}
    </script>

    <script src="{{ url_for('static', filename='js/inventories.js') }}"></script>

{% endblock %}

templates/inventory/inventory-table.html
{% if number_inventories > 0 %}
    <table class="table  dataTable" id="inventories-table">
        <thead class="success">
        <tr>
            <th></th>
            <th></th>
            <th></th>
            {% if user_is_authenticated %}
                <th></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for inventory_data in inventories %}
            {% if "__default__" not in  inventory_data['inventory_name'] %}
                <tr>
                    <td>
                        <a href="{{ url_for('items.items_with_username_and_inventory', username=inventory_data['inventory_owner'], inventory_slug=inventory_data['inventory_slug']) | replace('%40', '@') }}">
                            {{ inventory_data['inventory_name'] }}</a>
                    </td>
                    <td>{{ inventory_data['inventory_description'] }}</td>
                    <td>
                        {{ inventory_data['inventory_item_count'] }} item(s) | @{{ inventory_data['inventory_owner'] }}
                        |
                        {% if  inventory_data['inventory_public'] == 1 %}
                            <span class="fas fa-unlock" style="color:red;"
                                  data-toggle="tooltip" data-placement="top" title="This inventory is public"
                            ></span>
                        {% else %}
                            <span class="fas fa-lock"
                            data-toggle="tooltip" data-placement="top" title="This inventory is not public"
                            ></span>
                        {% endif %}
                        {% if inventory_data['inventory_access_level'] == 1 %}
                            | User
                        {% elif inventory_data['inventory_access_level'] == 2 %}
                            | Viewer
                        {% endif %}
                    </td>

                    {% if user_is_authenticated %}
                        <td>
                            <span class="fas fa-edit fa-2x" data-bs-toggle="collapse"
                                  id="inventoryEdit-{{ inventory_data['inventory_id'] }}"
                                  href="#collapseInventoryEdit"
                                  data-inventory-id="{{ inventory_data['inventory_id'] }}"
                                  data-inventory-name="{{ inventory_data['inventory_name'] }}"
                                  data-inventory-description="{{ inventory_data['inventory_description'] }}"
                                  data-inventory-slug="{{ inventory_data['inventory_slug'] }}"
                                  data-inventory-public="{{ inventory_data['inventory_public'] }}"


                                  data-toggle="tooltip" data-placement="top" title="Edit inventory"
                                  style="display: inline-block; margin-right: 20px;"></span>

                            <span id="delete-inventory-btn-{{ inventory_data['inventory_id'] }}"
                                  data-bs-toggle="collapse"
                                  href="#confirmInventoryDelete-{{ inventory_data['inventory_id'] }}"
                                  class="fas fa-times fa-2x "
                                  data-toggle="tooltip" data-placement="top" title="Delete inventory"
                                  style="color:red; display: inline-block; margin-right: 20px;"></span>

                            <div class="collapse" id="confirmInventoryDelete-{{ inventory_data['inventory_id'] }}"
                                 aria-expanded="false">
                                <button type="button" class="btn btn-primary btn-sm"
                                        id="confirmInventoryDeleteBtn-{{ inventory_data['inventory_id'] }}"
                                        data-inventory-id="{{ inventory_data['inventory_id'] }}"
                                        data-inventory-slug="{{ inventory_data['inventory_slug'] }}">Confirm delete
                                </button>
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="row">
        <div class="col-md-12">
            <div class=" text-center">
                <h5>Oh no, no inventories :(</h5>

                <p>You can add a new inventory by clicking the <i class="fas fa-plus"></i> icon at the top.</p>
            </div>
        </div>
    </div>
{% endif %}