routes/field_template_routes.py
import collections
import json

import bleach
from flask import Blueprint, render_template, redirect, url_for, request, abort, Response, flash
from flask_login import login_required, current_user

from database_functions import find_template, add_new_template, update_template_by_id, get_user_templates, \
    get_all_fields, save_template_fields, get_user_template_by_id, delete_templates_from_db, \
    set_template_fields_orders, \
    get_template_fields_by_id

import strings

field_template = Blueprint('field_template', __name__)


@field_template.context_processor
def inject_front_end_strings():
    """
    Inject strings into the front end
    :return:
    """
    return dict(strings=strings)


@field_template.route('/field-templates')
@login_required
def templates():
    return templates_with_username(username=current_user.username)


@field_template.route(rule='/field-templates/<template_id>/sort', methods=['GET', 'POST'])
@login_required
def sort_template(template_id):
    if request.method == 'GET':
        all_fields = dict(get_all_fields())

        user_template_ = get_user_template_by_id(template_id=template_id, user_id=current_user.id)

        selected_field_ids = []
        if user_template_ is not None:
            for field_ in user_template_[0].fields:
                selected_field_ids.append(field_.id)

        sdds = get_template_fields_by_id(template_id=template_id)

        selected_field_ids = {}
        for entry in sdds:
            template_field_, field_ = entry

            selected_field_ids[template_field_.order] = {"name": field_.field, "id": field_.id}

        od = collections.OrderedDict(sorted(selected_field_ids.items()))

        return render_template(template_name_or_list='field_template/_sort_template_fields.html',
                               field_template_name=user_template_[0].name,
                               username=current_user.username, all_fields=all_fields, user_template=user_template_,
                               selected_field_ids=selected_field_ids, template_id=template_id, fields=od)

    else:
        json_data = request.json
        row_order = json_data["row_order"]
        set_template_fields_orders(field_data=row_order, template_id=template_id, user_id=current_user.id)

        return json.dumps({'success': True}), 200, {'ContentType': 'application/json'}


@field_template.route('/field-templates/<int:template_id>')
@login_required
def template(template_id):
    """
    :param template_id: The ID of the field template to retrieve.
    :return: The rendered template or a 404 error message if the template
    does not exist or the user does not have access.
    """
    all_fields = dict(get_all_fields())

    user_template_ = get_user_template_by_id(template_id=template_id, user_id=current_user.id)

    if user_template_ is None:
        return render_template(template_name_or_list='404.html', message="No such template or you do not have "
                                                                         "access to this item"), 404

    selected_field_ids = [field_.id for field_ in user_template_[0].fields]

    return render_template(template_name_or_list='field_template/field_template.html',
                           field_template_name=user_template_[0].name,
                           username=current_user.username, all_fields=all_fields, user_template=user_template_,
                           selected_field_ids=selected_field_ids, template_id=template_id)


@field_template.route('/@<username>/field-templates')
@login_required
def templates_with_username(username):
    all_fields = dict(get_all_fields())
    user_templates = get_user_templates(user=current_user)
    return render_template(template_name_or_list='field_template/field_templates.html',
                           name=current_user.username, templates=user_templates, all_fields=all_fields)


@field_template.route(rule='/set-template-fields', methods=['POST'])
@login_required
def set_template_fields():
    if request.method == 'POST':
        request_xhr_key = request.headers.get('X-Requested-With')
        if request_xhr_key and request_xhr_key == 'XMLHttpRequest':
            json_data = request.json
            template_name = json_data['template_name']

            # sanitise template name
            template_name = bleach.clean(template_name)

            field_ids = json_data['field_ids']
            if len(field_ids) == 0:
                abort(Response(response="At least 1 field is required for the template", status=400))

            field_ids = [str(x) for x in field_ids]

            save_template_fields(template_name=template_name, fields=field_ids, user=current_user)

    return redirect(url_for('field_template.templates'))


@field_template.route(rule='/field-templates/delete', methods=['POST'])
@login_required
def delete_template():
    json_data = request.json
    template_ids = json_data['template_ids']
    delete_templates_from_db(user_id=current_user.id, template_ids=template_ids)
    return redirect(url_for('field_template.templates'))


@field_template.route(rule='/field-templates/add', methods=['POST'])
@login_required
def add_template():
    """
    The `add_template` method is used to add or update a field template.
    It is a route function that handles a POST request to '/field-templates/add'.
    The method requires the user to be logged in.
    """
    template_id = request.form.get("template_id")
    template_name = request.form.get("template_name")
    template_fields = request.form.get("template_fields")

    if template_id is None:
        flash("Problem adding template.")
        return redirect(url_for('field_template.templates'))

    if template_name is None:
        flash("Problem adding template.")
        return redirect(url_for('field_template.templates'))

    new_template_data = {
        "id": template_id,
        "name": template_name,
        "fields": template_fields,
    }

    potential_template = find_template(template_id=int(template_id))

    if potential_template is None:
        template_, message = add_new_template(name=template_name,
                                              fields=template_fields, to_user=current_user)
        if template_ is None:
            flash("Problem adding template.")
            return redirect(url_for('field_template.templates'))
    else:
        status, message = update_template_by_id(template_data=new_template_data, user=current_user)
        if status is False:
            flash("Problem updating template.")

    return redirect(url_for('field_template.templates'))

templates/field_template/_add_template_form.html
<div class="col-12">
    <label for="form_template_name" class="form-label">Template name:</label>
    <input type="text" class="form-control" name="template_name" id="form_template_name" placeholder="" required>
</div>

<hr>

{% include 'field_template/field_selector.html' %}

<hr>

<input type="hidden" class="form-control" name="template_id" id="form_template_id" value="-1">
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
<div class="row">
    <div class="col-4">
        <button id="save-template-fields-btn" type="submit" class="btn btn-primary">Save</button>
        <button class="btn btn-primary">Cancel</button>
    </div>
    <div class="col-8">
        <div class="alert alert-danger alert-dismissible fade hide" role="alert" id="alert">
            <strong>Problem</strong> You need at least 1 field in your template.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    </div>
</div>

templates/field_template/_field_template_help.html
<p>Field templates are groups/sets of fields that can be defined and set to an inventory. These fields will be used when adding new items.</p>

<p>For example, you could define the following sets of fields for an inventory of computers: </p>

<ul>
    <li>Model</li>
    <li>Serial number</li>
    <li>Manufacturer</li>
    <li>Hard drive capacity</li>
    <li>...</li>
</ul>

<p>These fields would then be available to fill in when you add new items to that inventory.</p>

<p>You can add a new inventory by clicking the <i class="fas fa-plus"></i> icon at the top.</p>

<p>You can specify the sort order of the template fields using the <i class="fas fa-sort"></i> icon.</p>

templates/field_template/_sort_template_fields.html
{% extends "base.html" %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">

                         <div class="row">
                                <div class="col-md-12">
                                    <h4>Drag to sort the template fields</h4>
                                </div>
                         </div>

                            <div class="row">
                                <div class="col-md-11">

                                    <table class="table table-striped dataTable" id="sort-field-table">
                                        <thead class="success">
                                        <tr>
                                            <th></th>
                                            <th></th>
                                            <th>Field</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for field_order, field_data in fields.items() %}

                                                <tr>
                                                    <td>{{ field_order }}</td>
                                                    <td>{{ field_data['id'] }}</td>
                                                    <td>{{ field_data['name'] }}</td>
                                                </tr>

                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    <button id="save-order-btn" class="btn btn-primary">Save</button>

                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    {{ super() }}

    <script>
        $(document).ready(function () {
            let table = $('#sort-field-table').DataTable({
                "searching": false,
                paging: false,
                info: true,
                columnDefs: [
                    {targets: 0, visible: false},
                    {targets: 1, visible: false}
                ],
                rowReorder: {
                    selector: 'tr'
                }
            });

            table.on('row-reordered', function (e, diff, edit) {
                table.one('draw', function () {
                    console.log('Redraw occurred at: ' + new Date().getTime());

                    table.rows().every(function (rowIdx, tableLoop, rowLoop) {
                        console.log(rowIdx, this.data());
                    });

                });
            });

            $("#save-order-btn").on("click", function (e) {
                e.preventDefault();

                let row_order = {}
                table.rows().every(function (rowIdx, tableLoop, rowLoop) {
                    row_order[rowLoop] = this.data()
                });

                $.ajax({
                    type: "POST",
                    url: "{{ url_for('field_template.sort_template', template_id=template_id)}}",
                    contentType: 'application/json;charset=UTF-8',
                    headers: {
                        "X-CSRFToken": "{{ csrf_token() }}",
                    },
                    data: JSON.stringify(
                        {
                            'row_order': row_order
                        }
                    ),
                    success: function () {
                        window.location.href = "{{ url_for('field_template.templates')}}"
                    },
                    error: function () {
                        location.reload();
                    }
                });


            });

        });


    </script>

{% endblock %}

templates/field_template/_templates-table.html
{% if templates | length > 0 %}

    <table class="table table-striped dataTable" id="my-templates-table">
        <thead class="success">

        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        </thead>
        <tbody>
        {% for template in templates %}

            <tr>
                <td>
                     <a href="{{ url_for('field_template.template', template_id=template[0].id) }}">
                         {{ template[0].name }}</a>
                </td>

                <td>
                    {% for field in template[0].fields %}
                        {{ field.field }}
                        <br>
                    {% endfor %}
                </td>

            <td>
                 <a href="{{ url_for('field_template.sort_template', template_id=template[0].id) }}">
                 <span id="sort-template-span" class="fas fa-sort fa-2x" style=" display: inline-block; margin-right: 20px;"></span>
                     </a>
            </td>

            <td>

                <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" data-template-id="{{ template[0]['id'] }}"
                               id="selected-item-{{ template[0]['id'] }}">
                    </div>
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% else %}

    <div class="row">
        <div class="col-md-12">
            <div class=" text-center">
                <h5>No field templates defined :(</h5>
                <p>You can add a new template by clicking the <i class="fas fa-plus"></i> icon at the top.</p>
            </div>
        </div>
    </div>

{% endif %}

templates/field_template/add_template_form.html
<div class="col-12">
    <label for="form_template_name" class="form-label">Template name:</label>
    <input type="text" class="form-control" name="template_name" id="form_template_name" placeholder="" required>
</div>

<hr>

{% include 'field_template/field_selector.html' %}

<hr>

<input type="hidden" class="form-control" name="template_id" id="form_template_id" value="-1">
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
<div class="row">
    <div class="col-4">
        <button id="save-template-fields-btn" type="submit" class="btn btn-primary">Save</button>
        <button class="btn btn-primary">Cancel</button>
    </div>
    <div class="col-8">
        <div class="alert alert-danger alert-dismissible fade hide" role="alert" id="alert">
            <strong>Problem</strong> You need at least 1 field in your template.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    </div>
</div>

templates/field_template/edit_field_selector.html
<div class="overflow-auto" style="max-width: 100pc; max-height: 800px;">

    <div class="row">
        <div class="col-md-11">

            <table class="table table-striped dataTable" id="item-field-table">
                <thead class="success">
                <tr>
                    <th>Field</th>
                    <th>Include</th>
                </tr>
                </thead>
                <tbody>
                {% for item_field_name, field in all_fields.items() %}
                    <tr>
                        <td>{{ item_field_name }}</td>
                        <td>
                            <input type='hidden' name='selected_fields[{{ item_field_name }}]' value='good'/>

                            {% if field.id in selected_field_ids %}
                                <input class="form-check-input" type="checkbox" value="{{ item_field_name }}"
                                       id="selected-field-{{ field.id }}"
                                       data-itemfield-id="{{ field.id }}"
                                       checked>
                            {% else %}
                                <input class="form-check-input" type="checkbox" value="{{ item_field_name }}"
                                       id="selected-field-{{ field.id }}"
                                       data-itemfield-id="{{ field.id }}">

                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

</div>

templates/field_template/field_selector.html
<div class="overflow-auto" style="max-width: 100pc; max-height: 800px;">

    <div class="row">
        <div class="col-md-11">

            <table class="table table-striped dataTable" id="item-field-table">
                <thead class="success">

                <tr>
                    <th>Field</th>
                    <th>Include</th>
                </tr>

                </thead>
                <tbody>

                {% for item_field_name, field in all_fields.items() %}

                    <tr>
                        <td>{{ item_field_name }}</td>
                        <td>
                            <input type='hidden' name='selected_fields[{{ item_field_name }}]' value='good'/>

                            {% if field.id in inventory_default_fields %}
                                <input class="form-check-input" type="checkbox" value="{{ item_field_name }}"
                                       id="selected-field-{{ field.id }}"
                                       data-itemfield-id="{{ field.id }}"
                                       checked>
                            {% else %}
                                <input class="form-check-input" type="checkbox" value="{{ item_field_name }}"
                                       id="selected-field-{{ field.id }}"
                                       data-itemfield-id="{{ field.id }}">

                            {% endif %}

                        </td>
                    </tr>

                {% endfor %}

                </tbody>

            </table>

        </div>
    </div>

</div>

templates/field_template/field_template.html
{% extends "base.html" %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">


                            <div class="col-12">
                                <label for="form_template_name" class="form-label">Template name:</label>
                                <input type="text" class="form-control" name="template_name" id="form_template_name"
                                       placeholder="" value="{{ field_template_name }}" required>
                            </div>

                            <hr>

                            {% include 'field_template/edit_field_selector.html' %}

                            <hr>

                            <input type="hidden" class="form-control" name="template_id" id="form_template_id"
                                   value="-1">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <div class="row">
                                <div class="col-4">
                                    <button id="save-template-fields-btn" type="submit" class="btn btn-primary">Save
                                    </button>
                                    <button class="btn btn-primary">Cancel</button>
                                </div>
                                <div class="col-8">
                                    <div class="alert alert-danger alert-dismissible fade hide" role="alert" id="alert">
                                        <strong>Problem</strong> You need at least 1 field in your template.
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                aria-label="Close"></button>
                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    {{ super() }}

    <script>

        $(document).ready(function () {
            $('#item-field-table').DataTable({
                "searching": true,
                paging: false,
                ordering: true,
                info: true
            });
        });

        $("#save-template-fields-btn").on("click", function (e) {
            e.preventDefault();
            // clear the search table to make sure the table is complete
            let table = $('#item-field-table').DataTable();
            table.search('').draw();

            let template_name = $('#form_template_name').val();

            let csrf_token = "{{ csrf_token() }}";
            let all_checkboxes = $('input:checkbox[id^="selected-field-"]')
            let number_selected = [];
            $.each(all_checkboxes, function () {
                let $this = $(this);
                if ($this.is(":checked")) {
                    number_selected.push(parseInt($this.attr('data-itemfield-id')));
                }
            });

            if (number_selected.length === 0) {
                $('#alert').toggleClass("show");
                return
            }

            $.ajax({
                type: "POST",
                url: "{{ url_for('field_template.set_template_fields')}}",
                contentType: 'application/json;charset=UTF-8',
                headers: {
                    "X-CSRFToken": csrf_token,
                },
                data: JSON.stringify(
                    {
                        'field_ids': number_selected,
                        'template_name': template_name,
                        'username': "{{ username }}",
                    }
                ),
                success: function () {
                    window.location.href = window.location.origin + "/{{ url_for('field_template.templates_with_username', username=username) }}";
                },
                error: function (e) {
                    location.reload();
                }
            });

        });
    </script>

{% endblock %}

templates/field_template/field_templates.html
{% extends "base.html" %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="row">
                                <div class="col-md-8">
                                    <h4>Field templates <small>| {{ templates | length }}</small></h4>
                                </div>

                                <div class="col-md-4">
                                    <div class="text-end">

                                        <a id="add-location-btn" data-bs-toggle="collapse" href="#addTemplateCollapse"
                                           role="button" aria-expanded="false" aria-controls="addTemplateCollapse">
                                                <span id="add-templates-span" class="fas fa-plus fa-2x"
                                                      style=" display: inline-block; margin-right: 20px;"></span>
                                        </a>

                                        <a id="delete-templates-btn-collapse" data-bs-toggle="collapse"
                                           href="#collapseDeleteTemplates"
                                           role="button" aria-expanded="false"
                                           data-toggle="tooltip" data-placement="top" title="Delete template(s)"
                                           aria-controls="confirmTemplateDelete">
                                                <span id="delete-templates-span" class="fas fa-minus fa-2x"
                                                      style="color:lightgray; display: inline-block; margin-right: 20px;cursor: pointer;"></span>
                                        </a>

                                        <span class="fas fa-info fa-2x" data-bs-toggle="collapse"
                                              href="#collapseTemplateHelp"
                                              style="display: inline-block; margin-right: 20px;cursor: pointer;"></span>

                                    </div>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-md-12">

                                    <div class="collapse" id="addTemplateCollapse" aria-expanded="false">
                                        <div class="card card-body">
                                            {% include 'field_template/_add_template_form.html' %}
                                        </div>
                                    </div>

                                    <div class="collapse" id="collapseTemplateHelp" aria-expanded="false">

                                            {% include 'field_template/_field_template_help.html' %}

                                    </div>

                                    <div class="collapse" id="collapseDeleteTemplates" aria-expanded="false">
                                        <div class="text-center">
                                            <p>Do you really want to delete? This process cannot be
                                                undone.</p>
                                            <button id="confirm-delete-templates-btn" type="button"
                                                    class="btn btn-primary btn-sm">Delete
                                            </button>
                                            <button id="cancel-delete-templates-btn" type="button"
                                                    class="btn btn-primary btn-sm">Cancel
                                            </button>
                                            <hr>
                                        </div>
                                    </div>

                                    {% include 'field_template/_templates-table.html' %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    {{ super() }}

    <script src="{{ url_for('static', filename='js/thinglist.js') }}"></script>

    <script>

        $(document).ready(function () {

            check_checkboxes()

            $('#item-field-table').DataTable({
                "searching": true,
                paging: false,
                rowReorder: true,
                info: true
            });
        });

        $('input:checkbox[id^="selected-item-"]').on("click", function (e) {
            check_checkboxes();
        });

        $("#cancel-delete-templates-btn").on("click", function (e) {
            deselect_all_checkboxes("selected-item-")
            $("#collapseDeleteTemplates").collapse("hide");
        });

        function check_checkboxes() {
            let number_selected = checkbox_count("selected-item-")

            let delete_collapse_btn_selector = $('#delete-templates-btn-collapse');
            let delete_btn_selector = $('#delete-templates-btn');
            let delete_span_selector = $('#delete-templates-span');

            if (number_selected > 0) {
                delete_collapse_btn_selector.attr('href', '#collapseDeleteTemplates');
                delete_btn_selector.css("pointer-events", "auto");
                delete_span_selector.css('color', 'red');
                delete_btn_selector.prop('disabled', false);
                delete_collapse_btn_selector.prop('disabled', false);
                delete_btn_selector.attr('disabled', 'disabled');

            } else {
                $("#collapseDeleteLocations").collapse("hide");
                delete_collapse_btn_selector.removeAttr('href');
                delete_btn_selector.css("pointer-events", "none");
                delete_span_selector.css('color', 'lightgray');
                delete_btn_selector.prop('disabled', true);
                delete_collapse_btn_selector.prop('disabled', true);
                delete_btn_selector.removeAttr('disabled');

            }
        }

        $("#confirm-delete-templates-btn").on("click", function (e) {
            e.preventDefault();

            let selected_list = get_selected_checkbox_ids("selected-item-", "data-template-id")

            $.ajax({
                type: "POST",
                url: "{{ url_for('field_template.delete_template')}}",
                contentType: 'application/json;charset=UTF-8',
                headers: {
                    "X-CSRFToken": "{{ csrf_token() }}",
                },
                data: JSON.stringify(
                    {
                        'template_ids': selected_list,
                        'username': "{{ username }}",
                    }
                ),
                success: function () {
                    location.reload();
                },
                error: function () {
                    location.reload();
                }
            });
        });


        $("#save-template-fields-btn").on("click", function (e) {
            e.preventDefault();
            // clear the search table to make sure the table is complete
            let table = $('#item-field-table').DataTable();
            table.search('').draw();

            let template_name = $('#form_template_name').val();

            let csrf_token = "{{ csrf_token() }}";
            let all_checkboxes = $('input:checkbox[id^="selected-field-"]')
            let number_selected = [];
            $.each(all_checkboxes, function () {
                let $this = $(this);
                if ($this.is(":checked")) {
                    number_selected.push(parseInt($this.attr('data-itemfield-id')));
                }
            });

            if (number_selected.length === 0) {
                $('#alert').toggleClass("show");
                return
            }

            $.ajax({
                type: "POST",
                url: "{{ url_for('field_template.set_template_fields')}}",
                contentType: 'application/json;charset=UTF-8',
                headers: {
                    "X-CSRFToken": csrf_token,
                },
                data: JSON.stringify(
                    {
                        'field_ids': number_selected,
                        'template_name': template_name,
                        'username': "{{ username }}",
                    }
                ),
                success: function () {
                    location.reload();
                },
                error: function (e) {
                    location.reload();
                }
            });

        });

    </script>

{% endblock %}