routes/api_routes.py
from flask import Blueprint
from flask_login import login_required, current_user

from database_functions import get_all_itemtypes_for_user, get_all_user_locations, get_all_user_tags, \
    get_all_item_types, find_all_my_items

api_routes = Blueprint('api', __name__)


@api_routes.context_processor
def my_utility_processor():
    def item_tag_to_string(item_tag_list):
        tag_arr = []
        for tag in item_tag_list:
            tag_arr.append(tag.tag.replace("@#$", " "))
        return ",".join(tag_arr)

    return dict(item_tag_to_string=item_tag_to_string)


@api_routes.route(rule='/api/item-types', methods=['GET'])
@login_required
def user_item_types():
    user_itemtypes_ = get_all_itemtypes_for_user(user_id=current_user.id)
    return user_itemtypes_


@api_routes.route(rule='/api/user-items', methods=['GET', 'POST'])
@login_required
def user_items():
    user_items_ = find_all_my_items(logged_in_user=current_user)
    ret_items = []
    for item_ in user_items_:
        ret_items.append(f"{item_.slug}")

    return ret_items


@api_routes.route(rule='/api/locations', methods=['GET'])
@login_required
def locations():
    locations_ = get_all_user_locations(user=current_user)
    loc_array = []
    for loc_ in locations_:
        loc_array.append(f"location:{loc_.name.lower()}")

    tags_ = get_all_user_tags(user_id=current_user.id)
    for tag_ in tags_:
        loc_array.append(f"tags:{tag_.tag.lower()}")

    item_types_ = get_all_item_types()
    for item_type_ in item_types_:
        loc_array.append(f"type:{item_type_.name.lower()}")

    return loc_array


# @api_routes.route('/api/locations', methods=['GET'])
# @login_required
# def user_locations():
#     user_locations_ = get_all_itemtypes_for_user(user_id=current_user.id)
#     return user_locations_

routes/itemtypes_routes.py
import csv
import os
from io import StringIO

from flask import Blueprint, render_template, redirect, url_for, request, make_response
from flask_login import login_required, current_user

from app import app

from database_functions import get_all_itemtypes_for_user, find_type_by_text, \
    add_new_user_itemtype, delete_itemtypes_from_db
import strings

types = Blueprint('types', __name__)


@types.context_processor
def inject_front_end_strings():
    """
    Inject strings into the front end
    :return:
    """
    return dict(strings=strings)


@types.route('/item-types')
@login_required
def item_types():
    user_itemtypes = get_all_itemtypes_for_user(user_id=current_user.id, string_list=False)
    return render_template(template_name_or_list='types/item_types.html', username=current_user.username,
                           user_item_types=user_itemtypes)


@types.route(rule='/item-type/delete', methods=['POST'])
@login_required
def delete_item_type():
    if request.method == 'POST':
        json_data = request.json
        itemtype_ids = json_data['itemtype_ids']
        delete_itemtypes_from_db(itemtype_ids=itemtype_ids, user_id=current_user.id)
        return redirect(url_for('types.item_types'))


@types.route(rule='/item_type/add', methods=['POST'])
@login_required
def add_item_type():

    if request.method == 'POST':
        item_type_name = request.form.get("item_type_name")

        potential_item_type_ = find_type_by_text(type_text=item_type_name)

        if potential_item_type_ is None:
            add_new_user_itemtype(name=item_type_name, user_id=current_user.id)

        return redirect(url_for('types.item_types'))


@types.route(rule='/item-types/save', methods=['POST'])
@login_required
def itemtypes_save():
    username = current_user.username

    filename = f"{username}_itemtypes_export.csv"

    user_itemtypes = get_all_itemtypes_for_user(user_id=current_user.id, string_list=False)

    csv_list = [["#Type"]]

    for row in user_itemtypes:
        item_type = row.name
        if item_type != "None":
            csv_list.append([item_type])

    si = StringIO()
    cw = csv.writer(si)
    cw.writerows(csv_list)
    output = make_response(si.getvalue())
    output.headers["Content-Disposition"] = f"attachment; filename={filename}"
    output.headers["Content-types"] = "text/csv"
    return output


@types.route(rule='/item-types/load', methods=['POST'])
@login_required
def itemtypes_load():

    if request.method == 'POST':

        if request.files:
            uploaded_file = request.files['file']  # This line uses the same variable and worked fine
            filepath = os.path.join(app.config['FILE_UPLOADS'], uploaded_file.filename)
            uploaded_file.save(filepath)

            with open(filepath) as csvfile:
                line_count = 0
                reader = csv.reader(csvfile, delimiter=',', quotechar='"')
                for row in reader:

                    if line_count != 0:
                        item_type = row[0]

                        if item_type != "None":
                            potential_item_type_ = find_type_by_text(type_text=item_type)
                            if potential_item_type_ is None:
                                add_new_user_itemtype(name=item_type, user_id=current_user.id)

                    line_count += 1

    return redirect(url_for('types.item_types'))

templates/types/_add_itemtypes_form.html
<form class="row g-3" method="post" action="{{ url_for('types.add_item_type') }}">
    <div class="col-12">
        <input type="text" class="form-control" name="item_type_name" id="item_type_name" placeholder="" required>
    </div>
    <div class="col-12">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-primary">Save</button>
        <button class="btn btn-primary">Cancel</button>
    </div>
</form>

templates/types/_item_type_help.html
<p>Item types are broad categories describing your things. Examples include:</p>

<ul>
    <li>Computer</li>
    <li>Victorian fishing badger</li>
    <li>...</li>
</ul>

<p>You can add a new item type by clicking the <i class="fas fa-plus"></i> icon at the top.</p>

templates/types/_item_types_table.html
{% if user_item_types | length > 1 %}

    <table class="table table-striped dataTable" id="my-itemtypes-table">
        <thead class="success">

        <tr>
            <th></th>
            <th></th>
        </tr>

        </thead>
        <tbody>
        {% for user_item_type in user_item_types %}
            {% if user_item_type.name != "None" %}

                <tr>
                    <td>
                        <a href="{{ url_for('items.items_with_username_and_inventory', username=username, inventory_slug="all") | replace('%40', '@') }}?type={{ user_item_type.name }}">{{ user_item_type.name }}</a>
                    </td>

                     <td>

                <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" data-itemtype-id="{{ user_item_type.id }}"
                               id="selected-item-{{ user_item_type.id }}">
                    </div>
            </td>


                </tr>
            {% endif %}

        {% endfor %}
        </tbody>
    </table>

{% else %}

    <h5>:) No item types</h5>

{% endif %}

templates/types/add_itemtypes_form.html
<form class="row g-3" method="post" action="{{ url_for('types.add_item_type') }}">
    <div class="col-12">
        <input type="text" class="form-control" name="item_type_name" id="item_type_name" placeholder="" required>
    </div>
    <div class="col-12">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-primary">Save</button>
        <button class="btn btn-primary">Cancel</button>
    </div>
</form>

templates/types/import_itemtypes_form.html
<h5>Load CSV...</h5>
<div class="card card-body">
    <form method="POST" action="{{ url_for("types.itemtypes_load") }}"
          enctype="multipart/form-data">
        <input class="form-control" type="file" name="file">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <hr>
        <button type="submit" class="btn btn-primary">Load</button>
    </form>
</div>

templates/types/item_type_help.html
<p>Item types are broad categories describing your things. Examples include:</p>

<ul>
    <li>Computer</li>
    <li>Victorian fishing badger</li>
    <li>...</li>
</ul>

<p>You can add a new item type by clicking the <i class="fas fa-plus"></i> icon at the top.</p>

templates/types/item_types.html
{% extends "base.html" %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    <h4 class="mb-0">Item types <small>| {{ user_item_types | length -1 }}</small></h4>
                                </div>
                                <div class="col-md-3">

                                    <div class="text-end">

                                        <span class="fas fa-plus fa-2x" data-bs-toggle="collapse"
                                              href="#collapseAddItemType"
                                              style="display: inline-block; margin-right: 20px;"
                                        ></span>

                                        <a id="delete-itemtypes-btn-collapse" data-bs-toggle="collapse"
                                           href="#collapseDeleteItemTypes"
                                           role="button" aria-expanded="false"
                                           data-toggle="tooltip" data-placement="top" title="Delete item types(s)"
                                           aria-controls="confirmItemTypesDelete">
                                                <span id="delete-itemtypes-span" class="fas fa-minus fa-2x"
                                                      style="color:lightgray; display: inline-block; margin-right: 20px;cursor: pointer;"></span>
                                        </a>

                                        <span class="fas fa-info fa-2x" data-bs-toggle="collapse"
                                              href="#collapseItemTypeHelp"
                                              style="display: inline-block; margin-right: 20px;"></span>

                                    </div>

                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="collapse" id="collapseItemTypeHelp" aria-expanded="false">
                                        <div class="card card-body">
                                            {% include 'types/_item_type_help.html' %}
                                        </div>
                                    </div>

                                    <div class="collapse" id="collapseAddItemType" aria-expanded="false">
                                        <div class="card card-body">
                                            {% include 'types/_add_itemtypes_form.html' %}
                                        </div>
                                    </div>

                                    <div class="collapse" id="collapseDeleteItemTypes" aria-expanded="false">
                                        <div class="text-center">
                                            <p>{{ strings.delete_confirm_string }}</p>
                                            <button id="confirm-delete-itemtypes-btn" type="button"
                                                    class="btn btn-primary btn-sm">{{ strings.delete_string }}
                                            </button>
                                            <button id="cancel-delete-itemtypes-btn" type="button"
                                                    class="btn btn-primary btn-sm">{{ strings.cancel_string }}
                                            </button>
                                            <hr>
                                        </div>
                                    </div>

                                    {% include 'types/_item_types_table.html' %}

                                    <form id="form-export-itemtypes" method="POST" style="display: none;"
                                          action="{{ url_for("types.itemtypes_save", username=username) }}">
                                        <input type="hidden" class="form-control" name="username" id="form_username"
                                               value="{{ username }}">
                                        <button type="submit" class="btn btn-primary">{{ strings.export_string }}</button>
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

{% block footer %}
    {{ super() }}

    <script src="{{ url_for('static', filename='js/autoComplete.js') }}"></script>
    <script src="{{ url_for('static', filename='js/thinglist.js') }}"></script>

    <script>

        $(document).ready(function () {

            check_checkboxes()

            $('#my-itemtypes-table').DataTable({
                "searching": true,
                paging: false,
                ordering: true,
                info: true
            });

        });

        $('input:checkbox[id^="selected-item-"]').on("click", function (e) {
            check_checkboxes();
        });

        $("#cancel-delete-itemtypes-btn").on("click", function (e) {
            deselect_all_checkboxes("selected-item-")
            $("#collapseDeleteItemTypes").collapse("hide");
        });


        function check_checkboxes() {
            let number_selected = checkbox_count("selected-item-")

            let delete_collapse_btn_selector = $('#delete-itemtypes-btn-collapse');
            let delete_btn_selector = $('#delete-itemtypes-btn');
            let delete_span_selector = $('#delete-itemtypes-span');

            if (number_selected > 0) {
                delete_collapse_btn_selector.attr('href', '#collapseDeleteItemTypes');
                delete_btn_selector.css("pointer-events", "auto");
                delete_span_selector.css('color', 'red');
                delete_btn_selector.prop('disabled', false);
                delete_collapse_btn_selector.prop('disabled', false);
                delete_btn_selector.attr('disabled', 'disabled');

            } else {
                $("#collapseDeleteItemTypes").collapse("hide");
                delete_collapse_btn_selector.removeAttr('href');
                delete_btn_selector.css("pointer-events", "none");
                delete_span_selector.css('color', 'lightgray');
                delete_btn_selector.prop('disabled', true);
                delete_collapse_btn_selector.prop('disabled', true);
                delete_btn_selector.removeAttr('disabled');

            }
        }


        $("#confirm-delete-itemtypes-btn").on("click", function (e) {
            e.preventDefault();

            let selected_list = get_selected_checkbox_ids("selected-item-", "data-itemtype-id")

            $.ajax({
                type: "POST",
                url: "{{ url_for('types.delete_item_type')}}",
                contentType: 'application/json;charset=UTF-8',
                headers: {
                    "X-CSRFToken": "{{ csrf_token() }}",
                },
                data: JSON.stringify(
                    {
                        'itemtype_ids': selected_list,
                        'username': "{{ username }}",
                    }
                ),
                success: function () {
                    location.reload();
                },
                error: function () {
                    location.reload();
                }
            });
        });


        const autoCompleteJS = new autoComplete({
            selector: "#item_type_name",
            placeHolder: "Enter type...",
            data: {
                src: async (query) => {
                    try {
                        // Fetch Data from external Source
                        const source = await fetch(`{{ url_for('api.user_item_types')}}?query=${query}`);
                        // Data should be an array of `Objects` or `Strings`
                        const data = await source.json();

                        return data;
                    } catch (error) {
                        return error;
                    }
                },
                // Data source 'Object' key to be searched
                //keys: ["food"]
            },
            threshold: 0,
            resultsList: {
                element: (list, data) => {
                    if (!data.results.length) {
                        // Create "No Results" message element
                        const message = document.createElement("div");
                        // Add class to the created element
                        message.setAttribute("class", "no_result");
                        // Add message text content
                        message.innerHTML = `<span>Found No Results for "${data.query}"</span>`;
                        // Append message element to the results list
                        list.prepend(message);
                    }
                },
                noResults: true,
                maxResults: undefined,
            },
            resultItem: {
                highlight: true,
            },
            events: {
                input: {
                    selection: (event) => {
                        autoCompleteJS.input.value = event.detail.selection.value;
                    }
                }
            }
        });

        $("#export-itemtypes-btn").on("click", function (e) {
            e.preventDefault();
            $('#form-export-itemtypes').submit();
        });

    </script>

{% endblock %}

templates/types/item_types_table.html
{% if user_item_types | length > 1 %}

    <table class="table table-striped dataTable" id="my-inventories-table">
        <thead class="success">

        <tr>
            <th></th>
            <th></th>
        </tr>

        </thead>
        <tbody>
        {% for user_item_type in user_item_types %}
            {% if user_item_type.name != "None" %}

                <tr>
                    <td>
                        <a href="{{ url_for('items.items_with_username_and_inventory', username=username, inventory_slug="all") | replace('%40', '@') }}?type={{ user_item_type.name }}">{{ user_item_type.name }}</a>
                    </td>
                    <td>

                <span id="delete-itemtype-btn-{{ user_item_type.id }}"
                      data-bs-toggle="collapse"
                      href="#confirmItemTypeDelete-{{ user_item_type.id }}"
                      class="fas fa-times fa-2x "
                      style="color:red; display: inline-block; margin-right: 20px;"></span>

                        <div class="collapse" id="confirmItemTypeDelete-{{ user_item_type.id }}" aria-expanded="false">
                            <button type="button"
                                    class="btn btn-primary btn-sm"
                                    id="confirmItemTypeDelete-{{ user_item_type.id }}"
                                    data-itemtype-id="{{ user_item_type.id }}">
                                Confirm delete
                            </button>
                        </div>

                    </td>

                </tr>
            {% endif %}

        {% endfor %}
        </tbody>
    </table>

{% else %}

    <h5>:) No item types</h5>

{% endif %}