routes/auth_routes.py
import re
import uuid

from MySQLdb import OperationalError
from sqlalchemy.exc import SQLAlchemyError
from flask import current_app, Blueprint, render_template, request, flash, redirect, url_for
from app import db
from app import login_manager, flask_bcrypt, app
from flask_login import (login_required, login_user, logout_user, confirm_login)

from database_functions import find_user, save_new_user, find_user_by_token, activate_user_in_db, find_user_by_username, \
    find_user_by_email
from email_utils import send_email
from models import User
import strings

auth_flask_login = Blueprint('auth_flask_login', __name__, template_folder='templates')



@auth_flask_login.context_processor
def inject_front_end_strings():
    """
    Inject strings into the front end
    :return:
    """
    return dict(strings=strings)



@auth_flask_login.route(rule='/forgot-password', methods=['GET', 'POST'])
def reset_password_form():
    """
    Reset Password Form

    Handles the logic for resetting user passwords.

    Returns:
        template: 'auth/reset_password.html' - If the request method is 'GET'
        template: 'auth/reset_password.html' with flash message - If the username is empty
        template: 'auth/reset_password.html' with flash message - If unable to update the user token
        template: 'auth/login.html' with flash message - If the reset password email is sent successfully

    Method:
        GET:
            Renders the 'auth/reset_password.html' template.

        POST:
            Retrieves the username from the request form data.
            If the username is empty, renders the 'auth/reset_password.html' template with a flash message.

            Otherwise, finds the user with the given username or email.
            If the user exists, generates a confirmation token and updates the user's token in the database.
            If an error occurs during the database update, flashes a message and renders the 'auth/reset_password.html' template.

            Constructs the text and HTML bodies of the email using the 'email/user_registration.txt' and 'email/user_registration.html' templates and the username and confirmation token
    *.

            Sends the email with the subject "Password reset" to the user's email address.

            Flashes a message indicating that an email will be sent if the account exists.

            Renders the 'auth/login.html' template.
    """
    if request.method == "GET":
        return render_template('auth/reset_password.html')
    else:
        username = request.form.get('username', '').strip()
        if not username:
            flash("Username cannot be empty.")
            return render_template(template_name_or_list="auth/reset_password.html")

        potential_user = find_user_by_username(username) or find_user_by_email(username)
        if potential_user:
            user_email = potential_user.email
            confirmation_token = uuid.uuid4().hex
            confirmation_token = flask_bcrypt.generate_password_hash(confirmation_token)
            potential_user.token = confirmation_token
            try:
                db.session.commit()
            except SQLAlchemyError as err:
                current_app.logger.error(msg=f"Error updating user token: {str(err)}", exc_info=True)
                flash("Unable to reset password")

            text_body = render_template(template_name_or_list='email/user_registration.txt', user=username,
                                        token=confirmation_token)
            html_body = render_template(template_name_or_list='email/user_registration.html', user=username,
                                        token=confirmation_token)
            send_email(subject="Password reset", sender=app.config['ADMINS'][0], recipients=[user_email],
                       text_body=text_body, html_body=html_body)

        flash("If this account exists, an email will be sent with instructions to reset the password")
        return render_template(template_name_or_list="auth/login.html")


@auth_flask_login.route(rule='/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    """
    Args:
        token: The token generated for password reset.

    Returns:
        None

    This method handles the password reset functionality. It expects a token parameter to be passed in the URL. If the request method is GET, it renders the 'new_password.html' template
    *. If the request method is POST, it retrieves the supplied password from the form, sanitizes it, and generates a password hash using flask_bcrypt.

    It then searches for a user with the provided token using the 'find_user_by_token' method. If a user is found and the user is not activated and the user's token matches the provided
    * token, it updates the user's password with the generated password hash and commits the changes to the database. If there is an error during the update, an error message is logged and
    * a flash message is displayed indicating that the password reset was unsuccessful.

    If no user is found or if the user is already activated or the user's token does not match the provided token, a flash message is displayed indicating that the password reset was unsuccessful
    *.

    Finally, it renders the 'login.html' template.
    """
    if request.method == "GET":
        return render_template('auth/new_password.html')
    else:

        supplied_password = sanitize(request.form.get("password"))
        # generate password hash
        password_hash = flask_bcrypt.generate_password_hash(supplied_password)

        supplied_token = flask_bcrypt.generate_password_hash(token)
        user_ = find_user_by_token(token=supplied_token)

        if user_ is not None and not user_.activated and user_.token == token:
            user_.password = password_hash
            try:
                db.session.commit()
            except SQLAlchemyError as err:
                current_app.logger.error(msg=f"Error updating user password: {str(err)}", exc_info=True)
                flash("Unable to reset password")

            flash("Password reset")
        else:
            flash("Unable to reset password")

        return render_template('auth/login.html')


def sanitize(input_string: str) -> str:
    """
    Sanitizes the given input string by encoding and decoding it using unicode_escape.

    Args:
        input_string (str): The input string to be sanitized.

    Returns:
        str: The sanitized input string.
    """
    # Perform input sanitization
    return input_string.encode('unicode_escape').decode()


@auth_flask_login.route(rule="/login", methods=["GET", "POST"])
def login():
    """
    Method: login

    This method is used to authenticate a user and log them into the system.

    URL: /login
    Methods: GET, POST

    Parameters:
        - None

    Returns:
        - None
    """

    if request.method == "POST" and "username" in request.form:

        username = sanitize(request.form.get("username"))
        password = sanitize(request.form.get("password"))

        user = find_user(username_or_email=username)
        if user and flask_bcrypt.check_password_hash(user.password, password) and user.is_active:
            remember = request.form.get("remember", "no") == "yes"

            if user.activated == 0:
                flash("Account not activated")
                return render_template("auth/login.html")

            if login_user(user, remember=remember):
                return redirect(url_for('main.profile', username=user.username).replace('%40', '@'))
            else:
                flash("Unable to log you in")
        else:
            flash("Unable to log you in")

    allow_registrations = (int(app.config['ALLOW_REGISTRATIONS']) == 1)
    return render_template(template_name_or_list="auth/login.html", allow_registrations=allow_registrations)


@auth_flask_login.route(rule="/activate-user/<token>", methods=["GET"])
def activate_user(token):
    """
    Activate a user based on the given token.

    :param token: The activation token provided in the URL.
    :type token: str
    :return: The rendered template after user activation.
    :rtype: str
    """
    supplied_token = flask_bcrypt.generate_password_hash(token)
    user_ = find_user_by_token(token=supplied_token)
    template = "auth/login.html"

    if user_ is not None and not user_.activated and user_.token == token:
        status, msg = activate_user_in_db(user_id=user_.id)
        if status:
            flash("You are now an activated Thing!")
        else:
            flash("Unable to activate user")

    return render_template(template)


@auth_flask_login.route(rule="/passwd", methods=["GET", "POST"])
@login_required
def change_password():
    current_app.logger.info(request.form)

    if request.method == 'POST':

        username = request.form['username']

        try:
            user_ = find_user(username_or_email=username)
            if user_ is not None:
                confirmation_token = uuid.uuid4().hex
                confirmation_token = flask_bcrypt.generate_password_hash(confirmation_token)

                text_body = render_template(template_name_or_list='email/reset_password.txt', user=username, token=confirmation_token)
                html_body = render_template(template_name_or_list='email/reset_password.html', user=username, token=confirmation_token)
                send_email(subject="Password change", sender=app.config['ADMINS'][0], recipients=[user_.email],
                           text_body=text_body, html_body=html_body)

        except Exception as err:
            current_app.logger.error("Error on registration - possible duplicate emails")

        flash("If this account exists, an email will be sent with instructions to reset the password")
        return render_template("auth/reset_password.html")


    else:
        return render_template("auth/reset_password.html")

routes/index_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from database_functions import get_user_inventories, get_user_item_count, get_user_templates, \
    get_all_itemtypes_for_user, find_user_by_username, delete_notification_by_id, get_number_user_locations

import strings

main = Blueprint('main', __name__)


@main.context_processor
def inject_front_end_strings():
    """
    Inject strings into the front end
    :return:
    """
    return dict(strings=strings)

@main.route('/')
def index():
    """
    Redirects the user to their profile if they are logged in, otherwise renders the index.html template.

    :return: A redirect response to the profile page if the user is logged in, otherwise the rendered index.html template.
    :rtype: werkzeug.wrappers.response.Response or flask.templating.render_template.rendered_template
    """
    # Ensure that 'current_user' is instantiated correctly, usually done through LoginManager
    if current_user and current_user.is_authenticated:
        return redirect(url_for(endpoint='main.profile', username=current_user.username))
    else:
        return render_template('index.html')


@main.route('/about')
def about():
    """
    This method is a route handler for the '/about' endpoint. It renders the 'about.html' template and returns it as a response.

    Returns:
        Response: A Flask response object containing the rendered 'about.html' template.
    """
    return render_template('about.html')

@main.route('/privacy-policy')
def privacy():
    """
    Method privacy

        Method for rendering the privacy policy page.

    Returns:
        The rendered privacy policy page.

    """
    return render_template('privacy_policy.html')


@main.route(rule='/delete-notification>', methods=['POST'])
@login_required
def del_notification():
    """
    Deletes a notification by its ID.

    :return: None
    """
    json_data = request.json
    username = json_data.get('username')
    notification_id = json_data.get('notification_id')
    if notification_id is None:
        return "Missing 'notification_id'", 400
    delete_notification_by_id(notification_id=notification_id, user=current_user)

    return redirect(url_for(endpoint='main.profile', username=username))


@main.route('/@<username>')
@login_required
def profile(username):
    """
    :param username: The username of the profile being accessed.
    :return: The rendered profile page template with the user's information.
    """
    user_is_authenticated = current_user.is_authenticated
    current_user_id = None
    requesting_user_id = None

    # -1 for the default None item type
    num_item_types = len(get_all_itemtypes_for_user(user_id=current_user.id, string_list=False)) - 1
    num_items = get_user_item_count(user_id=current_user.id)
    num_field_templates = len(get_user_templates(user=current_user))
    num_user_locations = get_number_user_locations(user_id=current_user.id)

    if user_is_authenticated:
        current_user_id = current_user.id
        if username != current_user.username:
            user_ = find_user_by_username(username=username)
            if user_ is not None:
                requesting_user_id = user_.id
        else:
            requesting_user_id = current_user.id

    user_inventories = get_user_inventories(current_user_id=current_user_id, requesting_user_id=requesting_user_id,
                                            access_level=-1)

    user_notifications = current_user.notifications
    # -1 to remove the default inventory
    return render_template(template_name_or_list='profile.html', name=current_user.username, num_items=num_items,
                           num_item_types=num_item_types, username=username,
                           num_field_templates=num_field_templates, num_user_locations=num_user_locations,
                           user_notifications=user_notifications, user_is_authenticated=user_is_authenticated,
                           num_inventories=len(list(user_inventories))-1)

routes/search_routes.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user

from database_functions import search_items
import strings

search_routes = Blueprint('search', __name__)


@search_routes.context_processor
def inject_front_end_strings():
    """
    Inject strings into the front end
    :return:
    """
    return dict(strings=strings)


@search_routes.route(rule='/search', methods=['GET', 'POST'])
@login_required
def search():
    query_string = request.args.get('q')
    if query_string is not None:
        items = search_items(query=query_string, user_id=current_user.id)
        return render_template(template_name_or_list='search/search.html', items=items, q=query_string, username=current_user.username)
    return render_template('search/search.html')

templates/_notifications_table.html
{% if user_notifications | length > 0 %}
    <h5>Notifications</h5>
    <hr>
    <div>

        <table class="table collapse show dataTable" id="user-notifications-table">
            <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for notification in user_notifications %}

                <tr>
                    <td>@{{ notification.from_user.username}}</td>
                    <td>{{ notification.text }}</td>
                    <td>{{ notification.date }}</td>
                    <td>
                        <span id="delete-notification-btn-{{ notification.id }}" data-bs-toggle="collapse"
                                  href="#confirmNotificationDelete-{{ notification.id }}"
                                  class="fas fa-times fa-2x "
                                  style="color:red; display: inline-block; margin-right: 20px;"></span>

                        <div class="collapse" id="confirmNotificationDelete-{{ notification.id }}"
                                 aria-expanded="false">
                                <button type="button" class="btn btn-primary btn-sm"
                                        id="confirmNotificationDeleteBtn-{{  notification.id }}"
                                        data-notification-id="{{  notification.id }}">Confirm delete
                                </button>
                            </div>

                    </td>
                </tr>

            {% endfor %}
            </tbody>

        </table>

    </div>

{% else %}

    <div class="row">
        <div class="col-md-12">
            <div class=" text-center">
                <p>You have no notifications</p>
            </div>
        </div>
    </div>

{% endif %}

templates/_topbar.html
<div id="body" class="active">

    <ul class="nav navbar-white bg-white nav-pills justify-content-center">

        <li class="nav-item text-center"><a class="nav-link" href="{{ url_for('items.items') }}">
            <i class="grey mb-2 fas fa-th-list"></i>
            <p class="text-muted show-big">{{ strings.items_string }}</p></a>
        </li>

        <li class="nav-item text-center"><a class="nav-link" href="{{ url_for('search.search') }}">
            <i class="grey mb-2 fas fa-search"></i>
            <p class="text-muted show-big">{{ strings.search_string }}</p></a>
        </li>

        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/thinglist-logo-50pc.png') }}" alt="" height="75">
        </a>

        {% if current_user.is_authenticated %}

            <li class="nav-item text-center"><a class="nav-link"
                                                href="{{ url_for('main.profile', username=current_user.username) | replace('%40', '@') }}">
                <i class="grey mb-2 fas fa-at"></i>
                <p class="text-muted show-big">@{{ current_user.username }}</p></a>
            </li>

            <li class="nav-item text-center"><a class="nav-link" href="{{ url_for('auth_flask_login.logout') }}">
                <i class="grey mb-2 fas fa-sign-out-alt"></i>
                <p class="text-muted show-big">{{ strings.auth_logout_string }}</p></a>
            </li>

        {% else %}

            <li class="nav-item text-center"><a class="nav-link" href="{{ url_for('auth_flask_login.login') }}">
                <i class="grey mb-2 fas fa-sign-in-alt"></i>
                <p class="text-muted show-big">{{ strings.auth_login_string }}</p></a>
            </li>

        {% endif %}

    </ul>

</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}
                ThingList
            {% endblock %}
        </title>

        {% block metadata %}
            <meta property="og:title" content="{{ strings.title_string }}"/>
            <meta property="og:type" content="website"/>
            <meta property="og:image" content="{{ url_for('static', filename='img/thinglist-logo-50pc.png') }}"/>
            <meta property="og:url"
                  content="https://thinglist.org"/>
        {% endblock %}

        <link rel="icon" type="image/png" href="/img/favicons/favicon-16x16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/img/favicons/favicon-32x32.png" sizes="32x32">


        <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='vendor/fontawesome/css/fontawesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='vendor/fontawesome/css/solid.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='vendor/fontawesome/css/brands.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/master.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='DataTables/datatables.min.css') }}" rel="stylesheet"/>
        <link href="{{ url_for('static', filename='css/gallery.css') }}" rel="stylesheet">

        <link href="{{ url_for('static', filename='assets/css/ct-ultimate-gdpr.css') }}" rel="stylesheet" type='text/css'>

        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>

    {% endblock %}
</head>

<body>

<div class="wrapper">
    <div id="body" class="active">
        {% include '_topbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>

{% block footer %}
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='DataTables/datatables.min.js') }}"></script>

    <script src="{{ url_for('static', filename='assets/js/ct-ultimate-gdpr.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/init.js') }}"></script>


    <div id="footer">

        <div class="container text-center">
           <p> © 2023 ThingList.org | <a href="{{ url_for("main.about") }}">About</a></p>
        </div>
    </div>

{% endblock %}

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="content">
        <div class="container">
            <div class="card">
                <div class=" text-center">
                    <div class="row align-items-center">

                        <div class="col-12">
                            <img class="img-fluid"
                                 src="{{ url_for('static', filename='img/thinglist-logo-50pc.png') }}"
                                 alt="ThingList logo">

                            <p>{{ strings.front_page_line1|safe }}</p>

                            <p>{{ strings.front_page_line2|safe }}</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}


{% block title %}
    ThingList
{% endblock %}

{% block content %}

    <div class="content">
        <div class="container">

            <div class="row">

                <div class="col-md-3"></div>

                <div class="col-md-3">
                    <div class="card">
                        <a class="nav-link" href="{{ url_for('items.items_with_username', username=username) }}">
                            <div class="content">
                                <div class="row">
                                    <div class="dfd text-center">
                                        <i class="grey large-icon mb-2 fas fa-th-list"></i>
                                        <h4 class="mb-0">{{ num_items }}</h4>
                                        <p class="text-muted">THINGS</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="card">
                        <a class="nav-link" href="{{ url_for('inv.inventories_for_username', username=username) }}">
                            <div class="content">
                                <div class="row">
                                    <div class="dfd text-center">
                                        <i class="grey large-icon mb-2 fas fa-table"></i>
                                        <h4 class="mb-0">{{ num_inventories }}</h4>
                                        <p class="text-muted">INVENTORIES</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>

                <div class="col-md-3">

                </div>

            </div>

            <div class="row">

                <div class="col-md-4">
                    <div class="card">
                        <a class="nav-link" href="{{ url_for('types.item_types') }}">
                            <div class="content">
                                <div class="row">
                                    <div class="dfd text-center">
                                        <i class="grey large-icon mb-2 fas fa-stream"></i>
                                        <h4 class="mb-0">{{ num_item_types }}</h4>
                                        <p class="text-muted">ITEM TYPES</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card">
                        <a class="nav-link" href="{{ url_for('field_template.templates') }}">
                            <div class="content">
                                <div class="row">
                                    <div class="dfd text-center">
                                        <i class="grey large-icon mb-2 fas fa-columns"></i>
                                        <h4 class="mb-0">{{ num_field_templates }}</h4>
                                        <p class="text-muted">FIELD TEMPLATES</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card">
                        <a class="nav-link" href="{{ url_for('location.locations') }}">
                            <div class="content">
                                <div class="row">
                                    <div class="dfd text-center">
                                        <i class="grey large-icon mb-2 fas fa-location-arrow"></i>
                                        <h4 class="mb-0">{{ num_user_locations }}</h4>
                                        <p class="text-muted">LOCATIONS</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>

            </div>


            <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="content text-center">

                            <a id="move-items-btn" data-bs-toggle="collapse" href="#collapseUserSettings"
                               role="button" aria-expanded="false" aria-controls="moveInventory">
                                <i class="fas fa-user-cog fa-2x"></i>
                            </a>


                            <div class="collapse" id="collapseUserSettings" aria-expanded="false">

                                <hr>






                                <form action="/login" method="POST">
                                    <div class="mb-3 text-start">
                                        <label for="email" class="form-label">Username:</label>
                                        <input type="text" name="username" class="form-control"
                                               placeholder="Enter username"
                                               required="">
                                    </div>
                                    <div class="mb-3 text-start">
                                        <label for="password" class="form-label">Password:</label>
                                        <input type="password" name="password" class="form-control"
                                               placeholder="Password"
                                               required="">
                                    </div>

                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                    <button class="btn btn-primary shadow-2 mb-4">Login</button>
                                </form>









                            </div>


                        </div>
                    </div>
                </div>
            </div>


            <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="content">
                            {% include '_notifications_table.html' %}
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

{% block footer %}
    {{ super() }}

    <script>
        $(document).ready(function () {

            $('#user-notifications-table').DataTable({
                "searching": true,
                paging: true,
                ordering: true,
                info: true
            });

        });


        $('[id^=confirmNotificationDeleteBtn]').on("click", function (e) {
            e.preventDefault();

            let notification_id = $(this).attr('data-notification-id');

            $.ajax({
                type: "POST",
                url: "{{ url_for('main.del_notification')}}",
                contentType: 'application/json;charset=UTF-8',
                headers: {
                    "X-CSRFToken": "{{ csrf_token() }}",
                },
                data: JSON.stringify(
                    {
                        'notification_id': notification_id,
                        'username': "{{ username }}",
                    }
                ),
                success: function () {
                    location.reload();
                },
                error: function () {
                    location.reload();
                }
            });

        });


    </script>

{% endblock %}